info:
  name: get /api/application-documents/by-app-id/:applicationId
  type: http
  seq: 6
  tags:
    - ApplicationDocument

http:
  method: GET
  url: "{{baseUrl}}/api/application-documents/by-app-id/:applicationId"
  params:
    - name: applicationId
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Success
    request:
      url: "{{baseUrl}}/api/application-documents/by-app-id/:applicationId"
      method: GET
      params:
        - name: applicationId
          value: ""
          type: path
    response:
      status: 200
      statusText: OK
      body:
        type: text
        data: ""
