info:
  name: get /api/ApplicationCourseDetail/:id
  type: http
  seq: 5
  tags:
    - ApplicationCourseDetail

http:
  method: GET
  url: "{{baseUrl}}/api/ApplicationCourseDetail/:id"
  params:
    - name: id
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Success
    request:
      url: "{{baseUrl}}/api/ApplicationCourseDetail/:id"
      method: GET
      params:
        - name: id
          value: ""
          type: path
    response:
      status: 200
      statusText: OK
      body:
        type: text
        data: ""
