info:
  name: get /api/ApplicationCourseDetail
  type: http
  seq: 2
  tags:
    - ApplicationCourseDetail

http:
  method: GET
  url: "{{baseUrl}}/api/ApplicationCourseDetail"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Success
    request:
      url: "{{baseUrl}}/api/ApplicationCourseDetail"
      method: GET
    response:
      status: 200
      statusText: OK
      body:
        type: text
        data: ""
